### ISSUE TITLE
Bug Tracking Report

### ISSUE THREAD

**Issue by mlw6607** [ethanjurman/WebEngProject#6]
- [x] Number of Bugs Collected
- [x] Number of Open Bugs
- [ ] How has bug tracking and mitigation impacted the project?

**Comment by thenaterhood** [comment]
See R1 Bug Tracking Report in the drive
